### PR TITLE
Parse refactoring

### PR DESCRIPTION
**Pull request by davla**
- Should Config parsing fail if mandatory keys (`dotfiles`, `config`) are not present?

### CODE REVIEW

**Comment by deadc0de6** [comment]
Currently a config file is only valid if it contains the three base entries: `dotfiles`, `profiles` and `config`. However if default values are defined for any mandatory field/entry, we could consider that no entry is actually required for a config file to be valid.

**Comment by deadc0de6** [comment]
The `config` part already contains pretty much default values for all entries. For the `dotfiles` and the `profiles` entries, we could simply create valid empty contents if those are not present.

**Comment by davla** [comment]
Yeah, I do something like this:

```python
yaml_dict.setdefault(Settings.key_yaml, cls.default_settings.serialize())
yaml_dict.setdefault(Dotfile.key_yaml, {})
```

So, `config` has all default values and `dotfiles` is an empty dict.

**Comment by davla** [comment]
What's the purpose of `Cfg:_get_unique_key`?

It's used when adding a new dotfile via the `Cfg:new` method, but only if the new dotfile does not exist yet. This in turn implies that its `dst` attribute is not found in the `Cfg` instance dotfiles.  
Now, the key is the shortest not-yet-used portion of the dotfile's `dst`, so it's going to be unique just because the `dst` attribute has been checked unique before adding the dotfile

**Comment by deadc0de6** [comment]
It is for finding a unique key when the `longkey` option is `true` (see [import dotfiles](https://github.com/deadc0de6/dotdrop/wiki/usage#import-dotfiles)).

**Comment by deadc0de6** [comment]
For example importing `~/.mutt/colors` and then `~/.colors` with `longkey: false` would result in both keys being `d_colors` without `_get_unique_key`. With it both keys are unique (`d_colors` and `d_colors_1`).

**Comment by davla** [comment]
Ok, I didn't think of existing short keys

**Comment by davla** [comment]
I implemented the `import` dotdrop command on `CfgYaml` side. I think this is enough for you to start playing around. Indeed, it would be nice to have another branch I can target my pull request to, so that we don't pollute master. If you're ok, I'll open the pull request when you create the new branch.

What we don't have:
- `CfgYaml` is still very bare-bones: it only reads from a single yaml file, and only handles `config`, `dotfiles` and `profiles` (except for the part that import from ANY other file).
- `CfgYaml` doesn't _resolve_ things. The list of dotfiles in a profile is a list of strings, rather than a list of `Dotfile` objects, for example. There is a point for discussion here, as I don't think this is among `CfgYaml` responsibilities. Actually, resolving names at `CfgAggregator` level would solve the problem @weilbith had in #130: pretty much any name could be defined anywhere, as long as it's imported somewhere somehow. It's definitely more error-prone, but we can be very conservative and crash as soon as an error occurs. What do you think?
- Copying files around when `import`ing in dotdrop. In my opinion is out of scope in `CfgYaml`: it should only deal with managing YAML files, not with actually implementing the command. 

What we do have:
- `CfgYaml` can parse `config`, `dotfiles` and `profiles` to (not fully-resolved) `Settings`, `Dotfiles` and `Profile` objects.
- New `Dotfiles` can be added to `CfgYaml` instances.

Methods:
- `CfgYaml:parse(path)` - static method that parses the YAML file found in `path` and returns a `CfgYaml` instance
- `Cfg:new_dotfile(dotfile, profile)` - instance method which adds the passed dotfile to the given profile, propagating the addition all the way down to the YAML file. `dotfile` is only added if not already present, while `profile` is created and added if not found. Returns `False` if `profile` already contains `dotfile`, `True` otherwise.
  + `dotfile` is a `Dotfile` instance. I thought this would scale better than having `src`, `dst` and `link` as arguments to `Cfg:new_dotfile` and creating the instance in the method. This way, if we end up having another dotfile field necessary when importing in dotdrop, the method signature needs not to change. The dotfile key attribute can be set to `None`, as it will be overridden in `Cfg:new_dotfile`. `Dotfile`'s constructor has been changed accordingly to make `key` optional.
  + `profile` can be a a profile key given as a string, or a `Profile` instance. In the first case, the profiles in the `CfgYaml` instance are searched for one having the same key, while in the second one they are searched for a `Profile` _computing_ equal to the given one. This has an important consequence: if a `Profile` instance is passed, but it `is` not the same object as the one found in `CfgYaml`, `dotfile` is not added, as `CfgYaml:new_method` works on another object. If you never create profiles outside of `CfgYaml`, you should have no problems, though. 
- `CfgYaml.settings`, `CfgYaml.dotfiles`, `CfgYaml.profiles`:. Respectively, `Settings` instance for the `config` key, list of `Dotfile` instances for `dotfiles` key and list of `Profile` instances for `profiles` key.
- `CfgYaml:save`: flushes any changes to the YAML file to disk.

**Comment by weilbith** [comment]
> So, config has all default values and dotfiles is an empty dict.

I'm a bit confused by this. I would expect that all options for the `config` section are either defined in the "main" `.yaml` or are the default. What does it mean that for an imported `.yaml` this is default again? When does _dotdrop_ take which option? Or is it just for easy compatibility purpose and internally it is aware about the "main" options? I'm confused...

**Comment by davla** [comment]
You don't understand because we didn't say it. We're not there yet :smile: But it will be very likely that `config` options will be taken from the _main_ config file only

**Comment by deadc0de6** [comment]
@davla thanks a lot for your work, I created the branch [config-refactoring](https://github.com/deadc0de6/dotdrop/tree/config-refactoring) where you can target your PRs.

Thanks for describing what you've done, much appreciated, here are a few remarks/questions:

* for your point on `CfgYaml` not resolving things, I think it is the right approach. The *transformation* of a list of strings in objects for example is the responsibility of `CfgAggregator` as it has the understanding of the higher level. This was my original approch in #128. `CfgYaml` only parses yaml and resolves basic types (strings, dict, list, etc) while `CfgAggregator` does the higher level handling. 
* Yes it is a good idea to simply crash/raise an exception whenever something is not valid and declare the config file as invalid, sounds good to me.
* I'm not a big fan of the `profile` argument to `Cfg:new_dotfile(dotfile, profile)` being either an object or a string, I'd rather stick to one type of argument to avoid issues/misunderstandings and improve readability if you're ok. Thus I would suggest either by basic type (`src`, `dst`, `profile` as string, etc) or by object (`Profile` and `Dotfile`). I'd rather have basic types as having objects would suggest that the caller should construct the object before they even exist. Also those *temporary* object (their reference) might not even be valid when the method returns. But I'm open to discuss this of course.

I'll have a look at everything you did and start coding on the branch once you've done your PR and we will be able to discuss the next steps. Thanks again :+1:

**Comment by weilbith** [comment]
@davla [here](https://github.com/deadc0de6/dotdrop/pull/136#issuecomment-490576001)

**Comment by davla** [comment]
I see you go a bit more for "static typing". Fair enough. I'll make `profile` in `CfgYaml:new_dotfile()` string-only, as the `Profile` objects are making things quirky.

As for `dotfile`, my approach is more "ORM-like" (even though I don't like ORMs at all). I think of  `CfgYaml` as somehow a persistency layer, and the idea is that you give it an object (a `Dotfile` in this case), and it will make it persistent. Indeed, like in a database, the key is initially `None`, as the database itself is in charge of handling keys.

On the other hand, your idea is more "factory-method like", where objects creation is delegated to the persistency layer, so that no "loose objects" ever exist. This is good too.

Both of these are valid approaches, so let's stick to the one you are currently using, that is "factory-method like". My one request is to make it something like this:
```python
def new_dotfile(self, dotfile_args, profile):
    dotfile = Dotfile(**dotfile_args)
    ...

cfg_file.new_dotfile({'src': src, 'dst': dst}, profile)
```
This way we don't have to add arguments to `new_dotfile` if in the future something else can be specified when `import`ing a dotfile. But most importantly we don't need to keep the default values in sync between the `Dotfile` constructor and `new_dotfile`, as the ones from the constructor are used. As a side effect, it reads a bit better, as you can clearly see what is `src` and what is `dst`

**Comment by davla** [comment]
> @davla [here](https://github.com/deadc0de6/dotdrop/pull/136#issuecomment-490576001)

That's just internal. It allows dotdrop not to crash when you don't specify the `config` key. However, it will add all the keys with default values to the YAML file whenever you import a dotfile. Is this ok, @deadc0de6?

**Comment by deadc0de6** [comment]
@davla I'm fully ok with the kwargs on `new_dotfile`.

It is also ok for me to add all undefined keys with default values to the YAML when those are not specified. For now every entry in `config` has a default value so this is fine.

**Comment by davla** [comment]
Here we go.

I'd like to still use this PR to discuss any related matters after you merge. I'll open another one for my next step (Actons), but I wish to keep things separated.

**Comment by deadc0de6** [comment]
Sure either here or on a dedicated issue, as you wish.

I'll start digging in and let you know how it looks for my part. I'll probably create a list of tasks for what still needs to be done so we can have a better overview where we are and what is still needed to be able to fully integrate that into dotdrop.

Thanks :+1:

**Comment by deadc0de6** [comment]
@davla from what I read I really like the idea of where this is going.

Just FYI here's my todo list:

* Creation of multiple serialization/deserialization classes:
  * new class `Profiles` that would handle the creation of a list of `Profile` object from a dictionary
  * new class `Dotfiles` that would handle the creation of a list of `Dotfile` object from a dictionary
  * new class `Actions` that would handle the creation of a list of `Action` object from a dictionary
  * new class `Transformations` that would handle the creation of a list of `Transformation` object from a dictionary
  * new class Variables/DynVariables to handle the variables
* implement the `CfgAggregator` which will call the serialization/deserialization of each block (profiles, dotfiles, etc) and be the reference for any access to the config
* entirely remove the `Cfg` class
* Integrate that with the `Options` class
* allow each object to be able to serialize and deserialize itself (`Action`, `Dotfile`, `Profile`, etc)

I'll work on that but just wanted to know if you plan on coding #141 before I start or you want to wait for it (just to avoid conflicts and such).

**Pull request merged**
