### PR TITLE
Make dotdrop.sh pass all of the ShellCheck lints

### PR DESCRIPTION
**Pull request by SShrike**
Follow up from #7.

### CODE REVIEW

**Comment by deadc0de6** [comment]
Unfortunately this won't work, see
```
$ false || echo "test" && echo "exit"
test
exit
$ true || echo "test" && echo "exit"     
exit
```

Also commit e04100fca53e30e95f9ce5ae6204d1b92ed04bb9 will actually break the way dotdrop is meant to be initialized (see `Quick start:` in the [readme](https://github.com/deadc0de6/dotdrop/blob/master/README.md)).

Have you actually tested your code ?

**Comment by SShrike** [comment]
I've pushed changes fixing the problem you mentioned, sorry about that I didn't test it thoroughly enough. Also the change in commit [`e04100f`](https://github.com/deadc0de6/dotdrop/commit/e04100fca53e30e95f9ce5ae6204d1b92ed04bb9) actually reverts the path back to what it was, as I had accidentally forgot that I'd changed the path. You can see in the "files changed" tab that the `bin=` line isn't modified at all.
image

**Comment by deadc0de6** [comment]
Thanks !

One last change and I'll merge it.

Can you change `bash` to `sh` since it was requested for https://github.com/deadc0de6/dotdrop/issues/2 (NixOS) ?

**Comment by SShrike** [comment]
I *believe* this should work on NixOS, as it's calling bash through /usr/bin/env which if I remember correctly does exist.

**Comment by deadc0de6** [comment]
awesome thanks !

merged.

**Pull request merged**
