### PR TITLE
Option to ignore missing files update and compare

### PR DESCRIPTION
**Pull request by MarcelRobitaille**
I use `link_children` a lot, so when I `compare` or `update`, I get a lot (like, hundreds) of warnings that files are not in my dotdrop. This is by design, I don't want these warnings. So, I added an option to ignore them.

### CODE REVIEW

**Comment by deadc0de6** [comment]
I see the problem and think the idea of a *ignore any missing* works great. However I have a few remarks/questions regarding your PR

* while having a cli switch is nice, a global option in the config could be useful too (would apply to all dotfiles)
* what about having a config per dotfile as well (giving more granularity to the user on which dotfile can safely ignore missing and which one doesn't)
* any reason you changed the usage to a raw string?
* `must_ignore` is not handling ignores in the comparator (while it does in the updater)
* I think it's risky to consider that the second argument of `must_ignore` is always the dotfile in dotdrop if set

If you're ok, I would suggest I try to refactor your approach to reach the same result with something more robust.

**Comment by MarcelRobitaille** [comment]
Thanks for your feedback
- I was thinking about also putting this in the config file, but I wasn't quite sure how to do it. I will look into it.
- Raw string is to avoid `W605: invalid escape sequence '\|'`, `'\_'`, etc.
- I will also look into `must_ignore`

**Comment by deadc0de6** [comment]
Cool, thanks, let me know if you need any help. I can take care of the config part if you want.

Regarding the order of `paths` in `must_ignore` I would suggest to simply handle that upstream (by the caller of `must_ignore`) since `must_ignore` shouldn't even been called if the file doesn't exist in dotdrop and `ignore_missing` is set.

**Comment by MarcelRobitaille** [comment]
Ok, I'll look into that, thanks.

Did you happen to look at my other commits? I think it takes care of some of the stuff we talked about.

**Comment by MarcelRobitaille** [comment]
I don't know exactly how to handle it upstream. Even the arguments to `compare` are `left` and `right`. Is it save to assume that these are source and dest respectively?

**Comment by deadc0de6** [comment]
@MarcelRobitaille yes I agree the naming is really bad in the Comparator. I should refactor this. But as mentioned in the [comment](https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/comparator.py#L29): left is the dotdrop dotfile (in dotdrop) and right is the deployed file (in the filesystem).

The `updater` class has no notion of dotfile only a path to update, you could simply pass it a boolean to ignore missing instead of the whole dotfile object. Besides the rest sounds good.

Will you implement a [bash test case](https://github.com/deadc0de6/dotdrop/blob/master/CONTRIBUTING.md#testing-with-bash-scripts)?

**Comment by MarcelRobitaille** [comment]
I took the liberty of renaming some variables in comparator. And I moved the check upstream.

I tried to do something in updater a while ago, but with your comment now I think that the list of dotfiles is actually a list of paths, not a list of instances.

I can write tests.

**Comment by deadc0de6** [comment]
Nice, thanks a lot for your work!
Ping me if you need help

**Comment by MarcelRobitaille** [comment]
> I tried to do something in updater a while ago, but with your comment now I think that the list of dotfiles is actually a list of paths, not a list of instances.

I looked at it again and it is actually dotfiles. So updater should be working too. What is next?

**Comment by deadc0de6** [comment]
Thanks for your help! Well next step would be to implement two bash scripts for the tests of `update` and `ignore` against the new feature.

You can for example make a copy of [update-ignore.sh](https://github.com/deadc0de6/dotdrop/blob/master/tests-ng/update-ignore.sh) to `update-ignore-missing.sh` and adapt it for testing the *ignore missing* feature (provided as a cli switch, in the global config, in dotdrop entry, etc). And then do the same with [compare-ignore.sh](https://github.com/deadc0de6/dotdrop/blob/master/tests-ng/compare-ignore.sh) to `compare-ignore-missing.sh`. If you need more guidance, ping me.

[Here](https://github.com/deadc0de6/dotdrop/blob/master/CONTRIBUTING.md#testing-with-bash-scripts) are some minimal information on the tests-ng.

Those files are automatically called as part of the CI/CD and help to validate the feature and make sure it keeps working in the future.

I haven't gone through all your changes in depth yet but will as soon as I find some time.

Once the test are working and cover all the use-cases, we can merge this into master.

**Comment by MarcelRobitaille** [comment]
I know it's been a while, but I finally had a chance to write some tests for these changes. What's the next step?

**Comment by deadc0de6** [comment]
Nice! That sounds pretty good, last step is the doc but I can write it if you want. Just let me know.
Once we're good, I'll merge it, thanks again! Nice work!

**Comment by MarcelRobitaille** [comment]
I can write some docs too.

**Comment by MarcelRobitaille** [comment]
I think we're ready to merge. What do you think?

**Comment by deadc0de6** [comment]
Awesome, thanks a lot for your help!!

**Pull request merged**
