### PR TITLE
Import config

### PR DESCRIPTION
**Pull request by davla**
Here we come, the `import_configs` functionality we talked about in #113. Just as a brief recap, we have a new config key, `import_configs` which will merge in the content of one or more configuration files. Some details:
- Conflicting keys (defined in both configs, like dotfiles or profiles having the same name), are resolved by keeping the original value, the one from the _importing_ config file.
- Shell globs can be used to specify config file paths, which as usual are relative to the _importing_ config file.

Now, some notes about the pull request itself:
- The first two commits are refactoring in the `Cfg._parse` method. The first one uses stuff such as `dict.setdefault` and `dict.get` to remove some `if`conditions on dictionary keys. The second one uses the more Pythonic `try .. catch KeyError` (_ask for forgiveness not for permission_) to check if a key is defined and then provide a default if its value is `None`. However, it's not very readable, so it's better to assess whether it should be included to begin with.
- Beside the typos in the commit messages, the rest is pretty straightforward: external configs are recursively parsed by constructing a `Cfg` class and then the two `Cfg` objects are merged in the [`_merge_cfg`](https://github.com/davla/dotdrop/blob/import-config/dotdrop/config.py#L453) method, by merging dictionaries and lists instance members.
- Globbing uses the `recursive` flag in [`iglob`](https://docs.python.org/3.7/library/glob.html#glob.iglob). It's been introduced in Python 3.5, but I think this is not a problem.

### CODE REVIEW

**Comment by deadc0de6** [comment]
Nice, awesome job, thanks again for your help!

Here are a few points to discuss

* shouldn't dotdrop warn the user when a duplicate key is found? Or even fail since each dotfile/profile key should be unique across all configs
* yeah as you mentioned, the refactoring with `try ... except` looks less readable ... but I could live with it ;-)
* I never used `glob` but if dotdrop depends on it (the recursive flag), support for python 3.4 will be dropped. Any other alternatives? Or more generally, is this recursive behavior absolutely needed?

I noticed you improved (and sometimes fixed) the code at multiple places, thanks for that :+1:!

**Comment by davla** [comment]
- Recursive globbing refers to the double star in paths like `profiles.d/**/*.yaml`. It's definitely not an indispensable feature, but it's nice to have. [As you can see](https://github.com/davla/dotdrop/commit/ab6070) I handled it by not using recursive globbing if the Python version doesn't support it. An warning is issued as well, which turns to an error if a `**` is actually used.
- The _duplicate keys_ problem is a delicate one:
  + Some keys will basically always be duplicate. All the keys in `config` are. Right now I'm merging those as well, but it would actually be sensible not to. What do you think?
  + Failing with duplicate dotfiles is not an option in my opinion. It drastically impedes modularity, as you have to keep track which config imports which and whatnot. A warning would be a good idea, or maybe even an interactive choice. We could think of adding different behaviors than overriding, but that's too far ahead right now.

**Comment by deadc0de6** [comment]
The python fallback for `glob` is nice!

for duplicate keys:
* I agree, we shouldn't merge those and in a way they are not needed in *sub* config files
* ok for the warning then, sounds good to me

Thanks!

**Comment by davla** [comment]
So, what is merged in is exactly:
- Dotfiles
- Profiles
- Actions
- Transformation
- Write transformation
- Variables

And with variables comes a big question: when should dynamic variables be evaluated? Right now I evaluate them as I parse the imported config files, just for convenience. However, it could be better to do it at a different time. I don't really know when they are evaluated in other cases in dotdrop, neither I know the degree of flexibility you want to guarantee. For example, I don't know whether it makes sense to evaluate them _before_ an action/transformation is executed or _after_, or _both_. I need your help here.

Also, I totally focused on the Python representation, but I forgot to check that things actually work :sweat_smile: And of course they don't :expressionless:  
The `src` path in `Dotfile` is dynamically loaded at runtime relatively to the current `Cfg` `dotpath`, which is not correct any longer with imported configurations. I tried as a workaround to create `Dotfile` instances with absolute paths, but this breaks some tests. It will just require some time.

**Comment by deadc0de6** [comment]
Currently you are merging all elements (from the main and sub configs) in the `self.content` dictionary of the main config. This has the consequence that any subsequent commands (like `import`) will save the config dictionary (`self.content`) to the yaml file (`config.yaml`) and thus *physically* merging all the configs (from the main and the external configs) in the main yaml file.

Here's an example where the profiles are merged although I haven't tested actions and other entries.

main config:
```yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_import_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  import_configs:
  - ext1.yaml
dotfiles:
  f_int:
    dst: ~/.int
    src: int
profiles:
  hostname:
    dotfiles:
    - f_int
    include:
    - ext
```

sub-config
```yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_import_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_ext:
    dst: ~/.ext
    src: ext
profiles:
  ext:
    dotfiles:
    - f_ext
```

When running `./dotdrop.sh import ~/.vimrc`, both file will be merged and saved into `config.yaml`.
```yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  import_configs:
  - ext1.yaml
  keepdot: false
  link_dotfile_default: nolink
  link_import_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_int:
    dst: ~/.int
    src: int
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
profiles:
  ext:
    dotfiles:
    - f_ext
  hostname:
    dotfiles:
    - f_int
    - f_vimrc
    include:
    - ext
```

This is an issue and [I initially thought](https://github.com/deadc0de6/dotdrop/issues/113#issuecomment-483565053) it'd be interesting to have different classes to handle external config files:
* a config class handling the *representation* (after parsing/tweaking/evaluating) of all the elements, not linked to the underlying config file yaml dictionary
* a main config class for parsing the main config (the ones which includes others)
* a sub config class for handling sub/imported configs

The above approach allows to have two different layers to the config: one with the elements from the yaml files and one with their representation in dotdrop. Also this allows to handle sub-config differently than the main config (for example without the need to have the `config` entry) and it will hopefully help to add new elements more easily (for example when `import` is used).

It is quite some work and it will probably need some refactoring to get there. What do you think of the above approach?

Below are a few points to discuss too.

# dynvariables 

Currently the *dynvariables* are evaluated dynamically through the [get_variables](https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/config.py#L855) method which will lookup in `self.content` the entry for the dynvariables (as well as the profile's specific dynvariables if any). This method is called when dotdrop's [options](https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/options.py) are constructed (that is at the beginning of the program).
It is also internally called (within *config.py*) to allow templating on external variable loading, imported dotfiles keys and included profiles.

From what I read, you are merging all variables (local and external) into the `key_variables` entry in `self.content` so those should be automatically evaluated by [options.py](https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/options.py) when constructed.

I was thinking of to evaluating the dynvariables only once instead of evaluating them multiple times but will wait for your PR to finish before refactoring this.

# config entry

Regarding the `config` entry in external configs: Although those won't be merged, it seems these need to be there since you are using the same `Cfg` class. This is somehow weird since a user needs to have those defined in the external config (but they are just unused) or he/she removes them and the config is then not valid anymore. It is not optimal. Anyway we can do that more efficiently?

# pre-defined variables

The [pre-defined variables](https://github.com/deadc0de6/dotdrop/wiki/templating#available-variables) are currently duplicated and throwing a warning. Since these are to be there anyway, dotdrop should avoid warning the user for these duplicates. (these are defined in [_get_variables in config.py](https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/config.py#L900))

```
[WARN] Variable _dotdrop_workdir defined both in /tmp/dotdrop/config.yaml and /tmp/dotdrop/ext1.yaml: _dotdrop_workdir in /tmp/dotdrop/config.yaml used 
[WARN] Variable _dotdrop_dotpath defined both in /tmp/dotdrop/config.yaml and /tmp/dotdrop/ext1.yaml: _dotdrop_dotpath in /tmp/dotdrop/config.yaml used 
[WARN] Variable _dotdrop_cfgpath defined both in /tmp/dotdrop/config.yaml and /tmp/dotdrop/ext1.yaml: _dotdrop_cfgpath in /tmp/dotdrop/config.yaml used
```

# test and corner cases

If you think of any corner-cases or issues that may arise when merging configs/using external configs, don't hesitate to write them down. The best way is always to create a test use-case right away but I know that writing tests is not always fun so at least we have a list of what could go wrong.

**Comment by davla** [comment]
So, let's address everything one point at a time. Small things first:

## pre-defined variables
I filter the variable keys that issue a warning by excluding those starting with an underscore. I think that's the convention in dotdrop, it makes sense. It's kinda hard to get to see those warnings in the tests, they are quite verbose.

## dynvariables
Yeah, I think it's better to deal with this once this PR is finished.

## config entry
My idea of use case is that you have a config file, say `config-shell.yaml` which you use standalone. Then, you want to use some dotfiles/profiles from that in `config-work-root.yaml` and in `config-work-user.yaml`, which need to be different for permissions reasons. In this case, all config files need to be complete, otherwise they cannot be used standalone.  
What you're thinking of, without the `config` keys, is much like a _profile_ file, which we don't address yet. This type of file serves the only purpose of being imported, and is not meant to be a standalone config file.

## importing dotfiles
Here we come with the big guy.  
As you can see now, this was meant to be a quick-and-dirty feature, before the _big refactoring_ you are talking about. I'd like to do the minimum amount of work to see the `import_configs` feature working, and then move on to the refactoring you suggest.  
A quick way to solve the issue with saving the file would be to keep track of whether dotfiles, profiles, actions etc are defined in the `config.yaml` underlying a `Cfg` object, and filter the _external_ one out when saving the file. If you are ok with this approach, I'd proceed.  
Anyway, I'm seriously looking forward to start handling this properly. I won't leave you alone (aka letting you take all the fun).

**Comment by deadc0de6** [comment]
Oh ok, that use-case make sense then.
I agree, let's go on with a quick-and-dirty version and we'll improve that on the way. 
I'm ok with the approach of filtering out the external ones with saving. My point is that external config file elements shouldn't be merged in the main config file in the end.
Thanks again for your help on this!

**Comment by davla** [comment]
I've written a test that checks whether any key in the imported config file is saved in the importing config file, and the other way around: basically, the two files should not mix, eg. no key from the other one should be saved in the other.

As for the implementation, the problem arose with variables and profiles. With variables, I opted for another hack and I merged them in `ext_variables` and `ext_dynvariables` (checking for common keys in self.content first). For profiles, I implemented that boolean tracking property: since it's only used there I didn't spend too much time in checking whether I add it to dictionaries and in traversing self.content properly. It's all written in comments anyway.

**Comment by deadc0de6** [comment]
Nice, do you feel this is ready to be merged?
Once I merge I'll add a documentation saying it is still experimental and we'll see on a case-by-case basis how that feature is being used.

**Comment by davla** [comment]
Yeah, it's ready. Given that we want to refactor anyway to ease this feature, there's little point in testing it any further.

Isn't it better if I write the docs as well? So that we are sure to be on the same page

**Comment by deadc0de6** [comment]
Awesome, I'll merge this then, thanks!

Of couse you can do the doc if you wish to. I found that neat workaround for doing pseudo-PR on project's wiki: <https://gist.github.com/larrybotha/10650410>.

**Comment by deadc0de6** [comment]
I unfortunately had to revert this PR as it seems the `ALL` keyword in dotfiles is not handled correctly.

**Comment by deadc0de6** [comment]
I added a new test `tests-ng/dotfiles-all.sh` that should test this feature. Could you make sure that no other key feature of dotdrop gets broken by this PR, thanks!

**Comment by davla** [comment]
Yeah, I forgot to execute the bash tests. Sorry for that.

**Comment by deadc0de6** [comment]
No worries there were no tests for `ALL` anyway so it's my fault too. Can you fix the PR code for `ALL`?
I guess you will have to open a new PR though.

**Pull request merged**
