### PR TITLE
adding support for pre/post actions

### PR DESCRIPTION
**Pull request by ziirish**
Hi,

I discovered your project recently, thanks for your hard work, this is a so brilliant piece of software that is going to change my life!

Anyway, I had some trouble deploying my `.vimrc` dotfile due to the lack of `pre` actions to install dependencies for instance.

So here is a PR in order to support `pre` and `post` actions in the hope you and/or someone else find it useful.

### CODE REVIEW

**Comment by deadc0de6** [comment]
oh thanks, happy it helps :-)

That *pre*/*post* actions sound really nice, especially since I recently moved to vim-plug too!
Thanks a lot for your submission!

A few questions I have:
* I would use `key_dotfiles_actions` instead of hardcoding the string `actions` in [this line of config.py](https://github.com/ziirish/dotdrop/blob/a867a850d8a1e64c560bb11f45d51796d79fdabc/dotdrop/config.py#L112) and [this line](https://github.com/ziirish/dotdrop/blob/a867a850d8a1e64c560bb11f45d51796d79fdabc/dotdrop/config.py#L109), if that's ok with you?
* would it make sense to you not directly put all naked action into the `post` entry instead of having an [additional entry in the actions dictionary](https://github.com/ziirish/dotdrop/blob/a867a850d8a1e64c560bb11f45d51796d79fdabc/dotdrop/config.py#L151)? It would simplify [this part too](https://github.com/ziirish/dotdrop/blob/a867a850d8a1e64c560bb11f45d51796d79fdabc/dotdrop/dotdrop.py#L123).
* I'm not sure to understand why you are checking about the string *actions* in the `dotfile.trans` [here]( https://github.com/ziirish/dotdrop/blob/a867a850d8a1e64c560bb11f45d51796d79fdabc/dotdrop/dotdrop.py#L100) and [here](https://github.com/ziirish/dotdrop/blob/a867a850d8a1e64c560bb11f45d51796d79fdabc/dotdrop/dotdrop.py#L170). This `pre`/`post` actions are only in the `actions` item, not in the `trans` one, or am I missing something?
* The trans is stil a list [here](https://github.com/ziirish/dotdrop/blob/a867a850d8a1e64c560bb11f45d51796d79fdabc/dotdrop/dotfile.py#L11) since it doesn't change with this PR, no?

**Comment by ziirish** [comment]
Thanks for the review.

> - I would use key_dotfiles_actions instead of hardcoding the string actions in this line of config.py and this line, if that's ok with you?
> - I'm not sure to understand why you are checking about the string actions in the dotfile.trans here and here. This pre/post actions are only in the actions item, not in the trans one, or am I missing something?

Sure you/we can use `key_dotfiles_actions` instead of the hardcoded `action` key.
But since `Cfg._parse_actions` is used both to parse *actions* and *trans*, both are impacted by this change.
That's one of the reasons why I didn't explicitly pushed *naked* actions to the `post` list, because that would not make sense for *trans* which are by nature `pre` actions.

**Comment by deadc0de6** [comment]
Good point. 
What about clearly separating the actions from the transformations then. Now that we have *pre* and *post* actions it would make sense to create a specific class *Transformation* (a bit like *Action*) and have a different function for parsing transformations (`_parse_trans` or similar). This would more clearly separate the two *types* (actions vs transformations) and allow for a cleaner code in the end?

**Comment by ziirish** [comment]
Sure, I'll update the PR when I have some time to clean a bit this patch.

I'll explicitly attach *naked* actions to the `post` key then.

**Comment by deadc0de6** [comment]
Awesome, thanks! Let me know if I can be of any help.

**Comment by ziirish** [comment]
done

**Comment by deadc0de6** [comment]
nice thanks a lot!

**Pull request merged**
