### PR TITLE
snapcraft yaml, fixes #92

### LINKED ISSUE #92: docker or snap dotdrop?
What do you think about docker or snap dotdrop version?
IMHO Dotdrop biggest weakness lies within deploying and updating process, 
this way it could be simplify to one command install and automatic background updates.
for reference
https://docs.snapcraft.io/python-apps/6741
regards

### PR DESCRIPTION
**Pull request by mchwalisz**
I have created snapcraft config to make snap packages. It should work once it is published to snap store.

Do you want me to register it? I think it will be better if you do it, but feel free to add me as collaborator. 

As next step it is also possible to make [snapcraft build a snap from github](https://snapcraft.io/build)

### CODE REVIEW

**Comment by deadc0de6** [comment]
Oh, awesome, thanks a lot for your help! Much appreciated!
Sure I'll register it.

**Comment by deadc0de6** [comment]
@mchwalisz ok I've registered the name on snapcraft.io however I'm having trouble building the snap. I'm sorry I don't have much experiences in snaps.

I tried on debian stretch but ended up with an error of type `Unable to determine host OS version codename` even when launching snapcraft with `VERSION_ID=9 VERSION_CODENAME=stretch /snap/bin/snapcraft`.

I then tried on ubuntu 18.04 but ended up with following errors:
```
Files from the build host were migrated into the snap to satisfy dependencies that would otherwise not be met. This feature will be removed in a future release. If these libraries are needed in the final snap, ensure that the following are either satisfied by a stage-packages entry or through a part:
usr/lib/x86_64-linux-gnu/libmagic.so.1
The linker version '2.23' used by the base 'core' is incompatible with files in this snap:
    /home/user/dotdrop/packages/snap/prime/lib/x86_64-linux-gnu/libexpat.so.1.6.7 (2.25)
    /home/user/dotdrop/packages/snap/prime/usr/bin/python3.6 (2.25)
    /home/user/dotdrop/packages/snap/prime/usr/bin/python3.6m (2.25)
    /home/user/dotdrop/packages/snap/prime/usr/lib/x86_64-linux-gnu/libexpatw.so.1.6.7 (2.25)
```

Any idea what I'm doing wrong?

Were you able to build the snap with the `snapcraft.yaml`, if yes, with what OS/distro/version?

Thanks a lot for your help!

**Comment by mchwalisz** [comment]
I'm also beginner at snaps. I'm using Arch and had also troubles building on my system.

Ended up running it inside docker https://docs.snapcraft.io/build-on-docker/4158

The following should do the trick:
```
# Inside dotdrop root folder:
docker run --rm -v "$PWD":/build -w /build snapcore/snapcraft bash \
      -c "apt update && cd packages && snapcraft"
```

**Comment by deadc0de6** [comment]
I'm on arch too but went the lxc path with no success. I'll try with docker on my arch then, thanks!

**Comment by deadc0de6** [comment]
Thanks again for your help!
Dotdrop is now available on snap: <https://snapcraft.io/dotdrop>

**Pull request merged**
