### PR TITLE
Added manpage to binary

### PR DESCRIPTION
**Pull request by gpxlnx**
Hello,

Congratulations on your work on dotdrop. I'm packaging it for Debian and derivatives and would like to suggest a manual for the program.

I am sending the current version along with the source code for your analysis and changes if necessary.

This manual was generated using the txt2man program.

thank you for your attention

### CODE REVIEW

**Comment by deadc0de6** [comment]
@gpxlnx hello, that's pretty nice you're packaging it for Debian, thanks a lot for that!

The manpage looks good however I would change the following:

* remove my email from the manpage and replace it with my github profile: https://github.com/deadc0de6
* add somewhere in the manpage links to both dotdrop repository (https://github.com/deadc0de6/dotdrop) and to dotdrop main documentation (https://dotdrop.readthedocs.io/)

The links could be added to an `ABOUT` section for example:
```
ABOUT
  More information can be found on dotdrop repository at https://github.com/deadc0de6/dotdrop and in the main documentation at https://dotdrop.readthedocs.io
```

What do you think?

**Comment by gpxlnx** [comment]
Hello,

Thanks for the feedback.
It will be a pleasure to bring your package to Debian and derivatives.

As for your suggestions, they can be done as suggested.

As per Debian policy you can incorporate this manpage into your source code. It is free and will follow the license you choose.

Would it be possible to include this manpage in the package source? This is necessary because otherwise I would have to create a patch in the package for it to be installed.

----
Best

**Comment by deadc0de6** [comment]
Sure, I'll refactor and add the manpage to the source. I'll then publish a new version of dotdrop with the manpage
* `manpage/dotdrop.txt`: the source for `txt2man`
* `manpage/dotdrop.1.ex`: nroff manpage generated from `manpage/dotdrop.txt`

I'll ping you when the new version is out.
Thanks again for your help

**Comment by gpxlnx** [comment]
Hi,

Good news, this is very cool.

As I said earlier, you can change the proposed information, generate the new manual page and insert it into your code if you wish.

We only need the dotdrop.1 file

If you want to use txt2man to do this, here is a small command used to generate this page.

Ex. txt2man -d "22 December 2022" -t dotdrop -r dotdrop-1.12.2 -s 1 -v "Save your dotfiles once, deploy them everywhere" dotdrop.txt > dotdrop.1

**Comment by deadc0de6** [comment]
Thanks a lot for your help!

I have created a manpage attempt on the [manpage branch](https://github.com/deadc0de6/dotdrop/tree/manpage/manpage).
Could you give it a look and let me know if that's good enough for a Debian package? I'm not sure how to use hyperlinks with `txt2man` but besides that I tried to stick to common manpages usages.

**Comment by gpxlnx** [comment]
Hello,

Its manpage is very well done and according to Debian standards.

I believe you can proceed with the merge and add the dotdrop.1 file to your project.

Congratulations and thanks for the help!!!

**Comment by deadc0de6** [comment]
@gpxlnx version [1.12.3 has been released](https://github.com/deadc0de6/dotdrop/releases/tag/v1.12.3) with its manpage:

<https://github.com/deadc0de6/dotdrop/tree/master/manpage>

Thanks again for your help on this and for creating a debian package for dotdrop :+1:

**Pull request closed without merging**
