### PR TITLE
Support for symlinking dotfiles

### PR DESCRIPTION
**Pull request by moyiz**
Maintaining dotfiles by editing the VC files, followed with './dotdtop.sh install' is not always convenient. I needed some dotfiles (like my vimrc) to be links.

Some of the dotfiles can be linked instead of copied to home directory.
Add 'link: true' to a dotfile section in order to link it.
Pay attention that template generation is not supported for dotfiles with 'link: true'!

I tested it manually, with and without '--dry' and it work as expected.

### CODE REVIEW

**Comment by deadc0de6** [comment]
Thanks a lot for your contribution. Indeed, it makes sense to have an option to link files instead of copying them (even if those couldn't be generated with templates).

It would nice if you could add some unittests for this feature along your PR in order to test the different behaviors with this (install when file exists, install when symlink exists, compare, install file, install folder, ...). Are you willing to do that ?

BTW I'm not sure to understand the reason to update the .gitignore ?

**Comment by deadc0de6** [comment]
I have some more open questions:
* I would suggest not to raise an exception when `remove` fails in order to avoid the entire installation process to fail. A way of doing this would be to return a boolean from `remove` and check it directly in `link`. Dotdrop would then display a warning with `self.log.err` and finally return `[]`. Does that make sense ?
* for the sake of coherence, would you agree using percent in string format instead of `.format` ?

**Comment by moyiz** [comment]
The reason I updated .gitignore is that running test.sh generated a .coverage file that wasn't covered in the previous gitignore file. I took the opportunity to replace it with a generic pythonic project gitignore file.

To answer (or discuss) the open questions:

- I don't think it matters. Before calling `utils.remove`, a file existence check is performed in `link`, so if the file does not exist, `utils.remove` would not be called.  I'm not sure I understand the second part of the first bullet. Why should `remove` return a boolean? At the end, what matters is that after `utils.remove` is called, no file should be present at `path`, so linking would be successful.  On top of that, if a file is present at the path and it is no the desired link, dotdrop asks the user to confirm the deletion of it, in order to replace it with a soft link. Isn't that the expected behavior?

- Of course.

I will work on adding some tests and try to post a new pull request in the next few days.
Another feature I missed here is a support for importing dotfiles as symlinks (without the need to import them and change configuration manually).

**Comment by deadc0de6** [comment]
Cool, thanks :smiley:

My point for the first bullet is twofold:

* `remove` could be called from somewhere else in the future where for example the file existence wouldn't be tested by the calling function. In that case I'd rather have a `remove` that returns a boolean telling if the file has been remove or not than an exception which could entirely stop/crash the program.
* `os.unlink` or `rmtree` might fail (think about permission issues, race conditions, etc) thus it'd be useful to return something like `os.path.exists(path)` and let the caller know if effectively the file has been deleted. Also enclosing those calls within try...catch would avoid any crash for the reasons above.

For those reasons I'd rather not raise exceptions from `remove`. Does it make more sense ?

Oh right, I forgot the `.coverage` on the .gitignore. I'll add it, thanks !

I can implement the part dealing with the import of *linked* dotfile (and the associated tests), no problem.

Thanks again for your help !

**Comment by moyiz** [comment]
I have wrapped `remove` in `try` and `except` as it should be used in my opinion. Would you still prefer a boolean indicator for the removal of a file?

I have also implemented support for `-l` or `--link`

**Comment by deadc0de6** [comment]
Wow that was fast :+1:

Everything looks good to me, ready to merge as soon as you push the tests.

Thanks again !!

**Comment by deadc0de6** [comment]
merged, thanks !

**Comment by deadc0de6** [comment]
I'm adding some repositories as examples in the readme, would you be ok if I add yours as a reference ?

**Comment by moyiz** [comment]
Of course, feel free to do so.

**Comment by deadc0de6** [comment]
thanks :+1:

**Pull request merged**
